stages:
  - build
  - release

build:
  stage: build
  script:
    - $Env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
    - 'nuget restore' 
    - 'msbuild /property:Configuration=Release' 
  artifacts:
    paths:
      - 'VisDbDig\bin\Release\VisDbDig.exe'
      - 'VisDbDig.Sql\bin\Release\VisDbDig.Sql.exe'
  tags : [windows]

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"Executable files\",\"url\":\"https://gitlab.com/patleahy/VisDbDig/-/jobs/artifacts/master/download?job=build\"}"
  rules:
    - if: $CI_COMMIT_TAG
